### ISSUE TITLE
mod is not working on 1.20.1 forge using forge version of azure lib

### ISSUE THREAD

**Issue by walksanatora** [cybercat-mods/HWG#94]
https://mclo.gs/WEsuoEW
> Caused by: java.lang.NoClassDefFoundError: mod/azure/azurelib/config/format/ConfigFormats
>   [✔] azurelib-neo-1.20.1-1.0.29

this function is probally omitted from forge due to forge allready having it's own config API
suggestion: implement this class (and possibly others) so that you can use the forge AzureLib with HWG

**Comment by walksanatora** [comment]
and if you try and use the fabric version of azure lib it hits you with the
> [modloading-worker-0/FATAL] [mixin/]: Mixin apply for mod (unknown) failed azurelib.mixins.json:fabric.PlayerListMixin from mod (unknown) -> net.minecraft.server.players.PlayerList: io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> azurelib.mixins.json:fabric.PlayerListMixin from mod (unknown) -> Apply Methods -> (Lnet/minecraft/network/Connection;Lnet/minecraft/server/level/ServerPlayer;Lnet/minecraft/class_8792;Lio/github/steelwoolmc/shadow/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V:handler$zcj000$configuration_sendServerConfigs -> Transform LVT -> var=commonListenerCookie -> desc=Lnet/minecraft/class_8792;]

**Comment by AzureDoom** [comment]
Forge AzureLib and Fabric Azurelib can't be mixed due to the difference in Item render registration. Remove AzureLib from you mods folder if you are using the connector build, that has it prebundled with it already.

That second issue shows you are using 1.20.2 AzureLib on 1.20.1,not an issue with HWG but a user issue.

**Comment by walksanatora** [comment]
still broken as when i downloaded
https://modrinth.com/mod/happiness-is-a-warm-gun/version/uxaEVXxn
it still depends on azure lib so my options are to either make a dummy mod which provides that ID or just remove it
I chose to just remove it from the dependicies field
and after i do that it then crashes with 
```
Caused by: java.lang.NoClassDefFoundError: mod/azure/azurelib/config/format/ConfigFormats
	at mod.azure.hwg.HWGMod.onInitialize(HWGMod.java:87) ~[hwg-depfix_mapped_srg_1.20.1.jar%23315!/:?] {re:classloading}
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23170!/:1.0.0-beta.15+1.20.1] {}
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.15+1.20.1-full.jar%23170!/:1.0.0-beta.15+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:56) ~[Connector-1.0.0-beta.15+1.20.1-mod.jar%23173!/:1.0.0-beta.15+1.20.1] {re:mixin,re:classloading}
	... 26 more
```
so ... have you tested or is this some obscure issue only occuring my machine or still user error?

**Comment by AzureDoom** [comment]
Considering I use it in my modpack here just fine that is running Forge and Connector builds of my various fabric-only releases: https://modrinth.com/modpack/doom-modpack/version/fTcrF8ow It's going to be an issue on your set up.
